# Generated by Django 5.2.7 on 2025-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='nombre_alerta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nivel_alerta',
            name='nivel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
