# Generated by Django 5.2.7 on 2025-10-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0002_alerta_nombre_alerta_nivel_alerta_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='nivel',
        ),
    ]
