# Generated by Django 5.2.7 on 2025-10-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0003_remove_alerta_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('Alerta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dagran.alerta')),
                ('nivel_alerta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dagran.nivel_alerta')),
            ],
        ),
    ]
