# Generated by Django 5.2.7 on 2025-10-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0004_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='otro',
        ),
    ]
