# Generated by Django 5.2.7 on 2025-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0005_remove_reporte_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
