# Generated by Django 5.2.7 on 2025-10-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0006_alerta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
