# Generated by Django 5.2.7 on 2025-11-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dagran', '0007_alter_alerta_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
